LocalJS={}
LocalJS.Lang = {
    _data: {},
    get: function (e, t) {
      return t && "cs_CZ" == LocalJS.config.language
        ? this.czechHach(e, t)
        : this._data[e] || e;
    },
    has: function (e) {
      return e in this._data;
    },
    nget: function (e, t) {
      if (this._data[e + "#plural"]) {
        var o = this._data[e + "#plural"].split("|");
        return o[this._pluralIndex(t)];
      }
      return this._data[e] || e;
    },
    setData: function (e) {
      this._data = e;
    }
}
LocalJS.Lang.setData({
'auth.account_is_banned' : 'Account has been banned',
'auth.account_not_active' : 'Account is not activated',
'auth.email_not_found' : 'Wrong E-Mail or password',
'Date.after_second' : 'seconds',
'Date.after_second#plural' : 'second|seconds',
'date.d' : 'd',
'date.days' : 'Days',
'date.h' : 'h',
'date.hours' : 'Hours',
'date.m' : 'm',
'date.minutes' : 'Minutes',
'date.s' : 's',
'date.weeks' : 'Weeks',
'donate.footer' : 'Best regards, administration of the site ikalogs.ru.',
'donate.text1' : 'Dear users of ikalogs.ru. Last few years, we were providing, updating and maintaining the site at our own expense. Due to the site growth and increase of reports number, as well as increase of the cost for server rent, our project needs financial support for further maintenance and develop of the site. ',
'donate.text2' : 'Your help will give us an additional incentive to promote and improve the functionality of the site in the future.',
'donate.text3' : 'We are asking all of you, who are not indifferent, to help our project.',
'donate.thanks1' : 'Thank you for your help.',
'eror.Redirect_after' : 'Redirect after',
'error.403' : 'You do not have the required permissions to enter this page.',
'error.404' : 'The requested page does not exist.',
'error.500' : 'An internal server error.',
'error.Access_deny' : 'Access denied',
'error.Cannot_find' : 'I can\'t find!',
'error.Do_not_give_It_is_my' : 'Do not get! Mine!',
'error.Ooops' : 'Ooops...',
'error.Redirect_after' : 'Redirect after',
'error.Something_is_broken' : 'Something is broken',
'error.Unknow_error' : 'Unknow error',
'error.We_fix_it' : 'We already fix it!',
'error.Where_it?' : 'Where it?',
'error.Where_to_go?' : 'Where to go?',
'error.You_are_not_logged' : 'You are not logged',
'error.You_can_not' : 'You can\'t!',
'error.forbidden' : 'Access deny!',
'error.internal_server' : 'Server Error!',
'error.page_not_found' : 'Page not found!',
'error.report' : 'The program made ​​an error, worry and pray to God not required.',
'form.Date_is_not_valid' : 'Date is not valid',
'form.Field have wrong value' : 'Field have wrong value',
'form.Field may contain only digits' : 'Field may contain only digits',
'form.Field may contain only float num' : 'The value must be an integer or a float',
'form.Field may contain only letters a' : 'Field may contain only letters and digits',
'form.Field value must be valid date' : 'Incorrect date',
'form.Field value must be valid email' : 'Wrong address',
'form.Field value must be valid hostna' : 'Wrong address of the site',
'form.Password confirm does not match' : 'Password and confirm does not match',
'form.Please enter valid URL' : 'Please enter valid URL',
'form.This field is required' : 'This field is required',
'form.User_email_already_exist' : 'User with this E-Mail already exists',
'form.User_not_approved' : 'Your account has not been confirmed. To confirm click on the link in the letter that is sent to you after registration.',
'form.Wrong_CurPassword' : 'The current password is incorrect',
'form.emailAddressInvalidHostname' : 'Incorrect address',
'form.hostnameInvalidLocalName' : 'Incorrect address',
'form.hostnameLocalNameNotAllowed' : 'Incorrect address',
'form.hostnameUnknownTld' : 'Incorrect address',
'form.isEmpty' : 'Required field',
'form.notFloat' : 'You can only enter a float',
'form.regexNotMatch' : 'Not validate value',
'form.value is too long' : 'The value is too long',
'form.value is too short' : 'Value is too short',
'issue.Comment' : 'Comment',
'issue.Not_found' : 'This appeal is not found',
'issue.author' : 'Author',
'issue.author_support' : 'Support',
'issue.author_you' : 'You',
'issue.closed' : 'Closed',
'issue.common' : 'General questions',
'issue.create_report' : 'The problem with making the report',
'issue.error' : 'Error in the work of Site',
'issue.idea' : 'Genius idea',
'issue.not_auth' : 'Problems with authorization',
'issue.offer' : 'Proposed for cooperation',
'issue.open' : 'Open',
'issue.report' : 'The problem with the report',
'issue.resolved' : 'Resolved',
'issue.vulnerability' : 'Vulnerability on the site',
'mail.password_forgot' : 'Recovery password',
'main.Account_is_active' : 'Account is successfully activated.',
'main.Account_is_not_active' : 'Account is not activated',
'main.Active' : 'Active',
'main.Add_profile' : 'Add profile',
'main.Add_to_ally_search' : 'Add in the search for alliances',
'main.Add_to_favorite' : 'Add to favorite',
'main.Adding_message' : 'Adding message',
'main.Adding_page' : 'Add page',
'main.Adding_resource' : 'Adding resource',
'main.Adding_tranlate' : 'Adding translation',
'main.All_phrases_was_translated' : 'All phrases was translated',
'main.Allow' : 'Allow',
'main.Ally' : 'Alliance',
'main.Ally_added_to_form' : 'The Alliance has been added to the search form',
'main.And_more' : 'And more',
'main.Any' : 'Any',
'main.Archer' : 'Archer',
'main.Are_you_sure?' : 'Are you sure?',
'main.Aristocracy' : 'Aristocracy',
'main.Auth' : 'Authorization',
'main.Back' : 'Back',
'main.Back_to_short_log' : 'Back to short log',
'main.Ballista_ship' : 'Ballista ship',
'main.Balloon-Bombardier' : 'Balloon-Bombardier',
'main.Balloon_Carrier' : 'Balloon Carrier',
'main.BanTo' : 'Banned until',
'main.Banned' : 'Banned',
'main.Battering_Ram' : 'Battering Ram',
'main.Battle_all_vs_alone_land' : 'All vs alone on the land.',
'main.Battle_all_vs_alone_sea' : 'All vs alone on the sea',
'main.Battle_ally' : 'Battles alliance',
'main.Battle_ally_land' : 'Cooperative attack on the land',
'main.Battle_ally_sea' : 'Cooperative attack on the sea',
'main.Battle_alone_land' : 'Single battles on the land',
'main.Battle_alone_sea' : 'Single battles on the sea',
'main.Battle_most_daring_robbery' : 'The most daring pillage',
'main.Battle_reports' : 'Battle reports',
'main.Catapult' : 'Catapult',
'main.Catapult_Ship' : 'Catapult Ship',
'main.Change_password' : 'Change password',
'main.City' : 'City',
'main.City_name' : 'City name',
'main.Cleaning' : 'Cleaning',
'main.Cleaning_all' : 'Cleaning all',
'main.Cleaning_army' : 'Cleaning army',
'main.Cleaning_fleet' : 'Cleaning fleet',
'main.Clear_all_cache' : 'Clear cache',
'main.Close' : 'Close',
'main.Code_of_Honour' : 'Code of Honour',
'main.Cook' : 'Cook',
'main.Coords' : 'Coordinates',
'main.Count' : 'Count',
'main.Current_password' : 'Current password',
'main.Date' : 'Date',
'main.Defence_points' : 'Defence points',
'main.Deleting' : 'Deleting',
'main.Democracy' : 'Democracy',
'main.Deny' : 'Forbidden',
'main.Detailed_battle_report' : 'Detailed battle report',
'main.Dictatorship' : 'Dictatorship',
'main.Difference_in_points' : 'Difference in points',
'main.Difference_in_resources' : 'The difference in resources',
'main.Direct_link' : 'Direct link',
'main.Diving_boat' : 'Diving boat',
'main.Doctor' : 'Doctor',
'main.Download' : 'Download',
'main.Edit_language' : 'Edit languages',
'main.Edit_menu' : 'Edit menu',
'main.Edit_resources' : 'Edit resources',
'main.Editing_message' : 'Editing message',
'main.Editing_page' : 'Editing page',
'main.Editing_resource' : 'Editing resource',
'main.Editing_tranlate' : 'Edit translate',
'main.Email' : 'E-mail',
'main.Email_not_found' : 'E-Mail was not found',
'main.Enter_captcha' : 'Enter the text from the image',
'main.Enter_real_email' : 'Enter your (current) E-Mail address',
'main.Events' : 'Events',
'main.Favorites' : 'Favorites',
'main.Find' : 'Find',
'main.Fire_Ship' : 'Fire Ship',
'main.Fleet' : 'Fleet',
'main.Forgot' : 'Forgot password?',
'main.Gen_password' : 'Generate password',
'main.Generals' : 'Generals',
'main.Generals2' : 'Generals',
'main.Ground_troops' : 'Ground troops',
'main.Gyrocopter' : 'Gyrocopter',
'main.Hoplite' : 'Hoplite',
'main.Icon' : 'Icon',
'main.If_email_not_receive' : 'If you do not receive E-Mail for 5 minutes, please contact us',
'main.Ikacracy' : 'Ikacracy',
'main.Inactive' : 'Inactive',
'main.Island' : 'Island',
'main.Island_title' : 'Name of the island',
'main.Key' : 'Key',
'main.Lang' : 'Language',
'main.Left_phrases' : 'Remains not translated phrases',
'main.Lifetime_server' : 'The lifetime of the server',
'main.Link_to_forum_loot_type' : 'Link to forum, loot, type',
'main.Link_to_forum_with_loot' : 'Link to forum with loot',
'main.Link_to_forum_with_type' : 'Link to forum with the type of report',
'main.Link_to_round' : 'Link to round',
'main.Link_to_score_of_war' : 'Score of war (loot, difference loss, type)',
'main.Links_to_report' : 'Links to report',
'main.Lint_to_forum' : 'Link to forum',
'main.Lint_to_site' : 'Link to site',
'main.Log_in' : 'Login',
'main.Logistics' : 'Logistics',
'main.Logout' : 'Logout',
'main.Loot' : 'Loot',
'main.Loss_attack' : 'Loss attacking',
'main.Loss_defend' : 'Loss defending',
'main.Lost_by_resources' : 'Lost by resources',
'main.Lost_by_score' : 'Lost by score',
'main.Lost_short' : 'L',
'main.Maps' : 'Maps',
'main.Members' : 'Members',
'main.Merchant_Ships' : 'Merchant Ships',
'main.Militaristic_Future' : 'Militaristic Future',
'main.Morale' : 'Morale',
'main.Mortar' : 'Mortar',
'main.Mortar_Ship' : 'Mortar Ship',
'main.Name' : 'Name',
'main.Namespace' : 'Namespace',
'main.News' : 'News',
'main.Nick' : 'Nick',
'main.Nick_of_player' : 'Player name',
'main.No_parent' : 'No parent',
'main.Nomocracy' : 'Nomocracy',
'main.None' : 'None',
'main.Not_active' : 'Not activated',
'main.Not_found' : 'Not found',
'main.Now_you_can_login' : 'Now you can login',
'main.Offensive_points' : 'Offensive points',
'main.Oligarchy' : 'Oligarchy',
'main.Options' : 'Options',
'main.Order' : 'Position',
'main.Original' : 'Original',
'main.Paddle_Speedboat' : 'Paddle Speedboat',
'main.Page' : 'Page',
'main.Parent' : 'Parent',
'main.Password' : 'Password',
'main.Password_sended_to_email' : 'A new password sent to the E-Mail',
'main.Path' : 'Path',
'main.Pitch' : 'Pitch',
'main.Plural' : 'Plural form',
'main.Plural_1_item' : 'In the singular',
'main.Plural_2_item' : 'In the plural',
'main.Plural_must_be_fill' : 'Both fields must be filled',
'main.Points_of_offensive_defence' : 'Points of offensive/defence',
'main.Population' : 'Population',
'main.Print_of' : 'Show of',
'main.Profile' : 'Profile',
'main.Ram_Ship' : 'Ram Ship',
'main.Read_more' : 'Read more',
'main.Refresh_langs' : 'Refresh languages',
'main.Reg' : 'Registration',
'main.Reg_complete' : 'Registration complete',
'main.Reg_complete_hint_login' : 'For Login use the form at the top right corner.',
'main.Reg_complete_text' : 'You have successfully registered.',
'main.Register' : 'Register',
'main.Report' : 'Combat report',
'main.Report_not_found' : 'Combat report is not found.',
'main.Report_stat_table' : 'Summary table',
'main.Reports' : 'Reports',
'main.Request_password' : 'Request a password',
'main.Restore_password' : 'Restore password',
'main.Restore_password_mail' : 'Letter with instructions sent to E-Mail',
'main.Retype_password' : 'Retype password',
'main.Rm_from_favorite' : 'Delete from favourite',
'main.Rocket_Ship' : 'Rocket Ship',
'main.Role' : 'Role',
'main.Roles' : 'Roles',
'main.Rounds' : 'Rounds',
'main.Saving' : 'Saving',
'main.Score' : 'Score',
'main.Score_after' : 'Remains',
'main.Score_before' : 'Score before',
'main.Score_lost' : 'Losses',
'main.Score_of_war' : 'Score of war',
'main.Sea_maps' : 'Sea maps',
'main.Seafaring_Future' : 'Seafaring Future',
'main.Search' : 'Search',
'main.Search_results' : 'Search results',
'main.Select_server' : 'Select server',
'main.Select_subject' : 'Select subject',
'main.Select_world' : 'Select world',
'main.Server' : 'Server',
'main.Ship_maintenance' : 'Ship maintenance',
'main.Show_all' : 'Show all',
'main.Show_only_untranslated' : 'Show only not translated',
'main.Show_reports' : 'Show reports',
'main.Slinger' : 'Slinger',
'main.Sources_common' : 'Cooperative',
'main.Spearmen' : 'Spearmen',
'main.Stat' : 'Statistics',
'main.State' : 'Status',
'main.Status' : 'Status',
'main.Steam_Giant' : 'Steam Giant',
'main.Steam_Ram' : 'Steam Ram',
'main.Subject' : 'Subject',
'main.Sulphur_Carabineers' : 'Sulphur Carabineers',
'main.Support_mess_text' : 'Text of your message',
'main.Swordsman' : 'Swordsman',
'main.Technocracy' : 'Technocracy',
'main.Tender' : 'Tender',
'main.Theocracy' : 'Theocracy',
'main.Title' : 'Title',
'main.Top_farm_ally' : 'Top Alliance for pillage',
'main.Top_farm_player' : 'Top Player for pillage',
'main.Total' : 'Total',
'main.Total_2' : 'Total',
'main.Total_loot' : 'Cooperative loot',
'main.Tradegood' : 'Resourse',
'main.Translate' : 'Translate',
'main.Translate_execute_on' : 'Translation is done by',
'main.Translate_of_interface' : 'Translate of interface',
'main.Translated_list' : 'Translated list',
'main.Type' : 'Type',
'main.URL' : 'URL',
'main.URL_was_copied' : 'Link copied to the clipboard',
'main.Unknow_error' : 'Unknown error',
'main.Upkeep' : 'Upkeep',
'main.Upkeep_in_way' : 'Upkeep in way',
'main.Userbars' : 'Userbars',
'main.Users' : 'Users',
'main.Users2' : 'Users',
'main.Vacation' : 'VM',
'main.Vacation_short' : 'VM',
'main.Value' : 'Value',
'main.Version' : 'Version',
'main.We_supported_all_servers' : 'Logmakers works on all servers',
'main.Wonder' : 'Wonder',
'main.World' : 'World',
'main.You_have_no_userbars' : 'You have no any userbars',
'main.You_link_is_expire' : 'You link is expire',
'main.You_need_create_profile' : 'Create a player profile in the relevant section.',
'main.active' : 'Active',
'main.alone' : 'alone',
'main.army' : 'land',
'main.attacker' : 'Attacker',
'main.banned' : 'Banned',
'main.browser_is_out_of_date' : 'Your browser is outdated or does not support the necessary technology for the operation of the site.',
'main.by_Ally' : 'by allinces',
'main.by_City' : 'by city',
'main.capacity' : 'Capacity per merchant ship',
'main.city' : 'city',
'main.city#plural' : 'city|cities',
'main.combo' : '1vsAll',
'main.defender' : 'Defender',
'main.donate_win_title' : 'Donations and plans',
'main.error_403' : 'Not enough rights',
'main.fleet' : 'sea',
'main.from_Month' : 'By month',
'main.from_Today' : 'By today',
'main.from_Week' : 'By week',
'main.from_Year' : 'By year',
'main.from_Yesterday' : 'By yesterday',
'main.ike_all_servers' : 'All servers',
'main.ike_desription' : 'IkaEasy - a connection in the one extension a lot of scripts for Ikariam. To use it do the following:',
'main.ike_download_browser' : 'Download browser',
'main.ike_download_gch_and_ike' : 'Open browser Google Chrome and download IkaEasy',
'main.ike_ext_for_browser ' : 'Extension for Google Chrome IkaEasy',
'main.ike_exten_version' : 'Version of extension',
'main.ike_logo_description' : 'extension for Google Chrome',
'main.ike_or_alternative' : 'or its alternatives',
'main.ike_support_ikar' : 'Support of Ikariam',
'main.ike_support_server' : 'Support of servers',
'main.loading' : 'Loading',
'main.mc_disable_counting_fleet' : 'Disable counting of of the fleet',
'main.mc_disable_counting_units' : 'Disable the counting of troops',
'main.mc_sum' : '∑',
'main.members' : 'member',
'main.members#plural' : 'member|members',
'main.no_reports' : 'You have no any report',
'main.not_active' : 'Not activated',
'main.or' : 'or',
'main.out_of' : 'out of',
'main.player' : 'player',
'main.player#plural' : 'player|players',
'main.please_wait' : 'Please wait',
'main.records' : 'records',
'main.records#plural' : 'record|records',
'main.res_crystal' : 'Crystal',
'main.res_marble' : 'Marble',
'main.res_sulphur' : 'Sulphur',
'main.res_wine' : 'Wine',
'main.res_wood' : 'Wood',
'main.sab' : 'ca',
'main.save_battle_reports' : 'save battle reports',
'main.screenshot' : 'screenshot',
'main.site_upgrade' : 'We update our site. Will be back soon.',
'main.switcher_archive' : 'Archive',
'main.switcher_normal' : 'Normal',
'main.to_Add_message' : 'Add message',
'main.to_Add_resource' : 'Add resource',
'main.to_Add_translate' : 'Add a translation',
'main.to_Cancel' : 'Cancel',
'main.to_Choose_type' : 'Choose type',
'main.to_Clear_cache' : 'Clear cache',
'main.to_Delete' : 'Delete',
'main.to_Edit' : 'Edit',
'main.to_Save' : 'Save',
'main.to_Search_all_city_player' : 'Find all cities the player',
'main.to_Send' : 'Send',
'main.to_Translate' : 'translate',
'main.translate_from' : 'from',
'main.translate_to' : 'to',
'main.triton' : 'Triton Engines',
'main.use_adblock' : 'We discovered that you are using AdBlock. Our site is now in a very difficult situation and needs funds derived from advertising. <br/>\
Please add our site to the exceptions if you are not indifferent to his fate.',
'main.wonder_total_faith' : '∑ levels of faith',
'menu.Admin' : 'Admin zone',
'menu.Barracks' : 'Barracks',
'menu.Hideout' : 'Hideout',
'menu.IkaEasy' : 'IkaEasy',
'menu.Reg' : 'Registration',
'menu.Room' : 'Room',
'menu.Scripts' : 'Scripts',
'menu.Tools' : 'Tools',
'menu.Top_lists' : 'Top-lists',
'menu.Translate' : 'Translation',
'role.admin' : 'admin',
'role.dev' : 'Developer',
'role.guest' : 'Guest',
'role.moderator' : 'Moderator',
'role.translator' : 'Translator',
'role.user' : 'User',
'script.Chrome_0' : 'Ikalogs integrated into IkaEasy',
'script.Chrome_1' : 'Download IkaEasy',
'script.Chrome_1_Ikalogs' : 'Download the extension from Chrome Web Store',
'script.Chrome_2' : 'Agree with the installation extension on your computer',
'script.Chrome_3' : 'Extension is installed',
'script.Firefox_1' : 'Install',
'script.Firefox_2' : 'Download the script',
'script.Firefox_3' : 'Agree with the installation script on your computer',
'script.Firefox_4' : 'The script is installed',
'script.New_Opera_1' : 'Install',
'script.Opera_1' : 'Create a folder on your PC',
'script.Opera_2' : 'In the settings of your browser specify the path to this folder',
'script.Opera_3' : 'Download the script and copy it to the folder you specified',
'script.Opera_4' : 'The script is installed',
'script.ikaeasyDescription' : 'IkaEasy is a browser extension Google Chrome, which contains the most popular scripts for games ikariam.com. Here transporter is present resources, showing the level of buildings and much more.',
'support.Link_to_page' : 'Ссылка на страницу',
'support.Link_to_report' : 'Link to report',
'support.Need_email' : 'You must specify the E-Mail, which will be sent back.',
'support.create' : 'Create appeal',
'support.hint_' : 'To send a message to technical support, select from the list the subject of your request.',
'support.hint_common' : 'You can ask us any question regarding the project, not related to the priority themes of the list.',
'support.hint_create_report' : 'Before creating the notification, make sure you have the latest version of the extension! <br />\
<br />\
Attention! In order that we can resolve the problem, contact support message you want to send it from the browser in which you can not create a report! <br />\
<br />\
If there is a problem with just one report, but not with all the polls, so it is necessary to clarify the features of the report, such as the number of rounds, the type of report (Army / Navy, sub / single, etc.)',
'support.hint_error' : 'You found an error on the site? <br />\
<br />\
Specify link in the appropriate field on the page where you found an error, and describe in detail what is wrong, and the sequence of actions for catching errors. <br />\
<br />\
If the problem occurs only in one browser and / or operating system, be sure to include them in particular, or send an error message directly from the browser problem.',
'support.hint_idea' : 'Do you have a great idea? <br />\
<br />\
Try to describe it as detailed as possible. <br />\
<br />\
We do not promise that necessarily realize it, but we at least look at it, and if the idea is really worth, and will be useful to most players, we will make every effort to implement it.',
'support.hint_offer' : 'We are open to any suggestions. <br />\
Describe your offer and if it will suit us, we will contact you for more detailed discussions.',
'support.hint_report' : 'Insert the appropriate field link to report the problem, and in the description, describe the problem as detailed as possible.',
'support.hint_vulnerability' : 'Try to describe in detail the most vulnerability found you. If you have an idea how you can cure discovered vulnerability, we would be grateful if you specify it too.',
'support.thanks' : 'Your appeal is taken. Soon we will contact you.',
'tools.map' : 'World map',
'tools.mapDescription' : 'Map of the world will help you in building a military plan capture of a city. Show you what coordinates are located on the city of your alliance and whether they intersect with the enemy. And also help to calculate the time in which you said you distance swims.',
'tools.military' : 'Military calculator',
'tools.militaryDescription' : 'Using a calculator, you can calculate the units as needed resources and gold production on your Army (Navy). Learn how many points will occupy army generals (Navy), as well as what number of gold will be spent on the maintenance of troops (Navy), located in your cities, or when moving.',
'tools.wonder' : 'Wonders calculator',
'tools.wonderDescription' : 'Using the "Calculator Wonderland" you can calculate with accuracy cooldown miracle with several temples.',
'wonder.1' : 'Hephaistos` Forge',
'wonder.2' : 'Hades` Holy Grove',
'wonder.3' : 'Demeter`s gardens',
'wonder.4' : 'Athena`s Parthenon',
'wonder.5' : 'Temple of Hermes',
'wonder.6' : 'Ares` stronghold',
'wonder.7' : 'Temple of Poseidon',
'wonder.8' : 'Colossus',
__dummy: ''});