drop table if exists alpha_town_units;
drop table if exists alpha_mission_units;
drop table if exists alpha_round_units;
drop table if exists alpha_missions;
drop table if exists alpha_rounds_data;
drop table if exists alpha_rounds_ui;
drop table if exists alpha_battles;
drop table if exists alpha_towns;
drop table if exists alpha_users;
