const UNITS = {
  0: "Hoplite",
  1: "Steam Giant",
  2: "Spearmen",
  3: "Swordsman",
  4: "Slinger",
  5: "Archer",
  6: "Sulfur Carabineers",
  7: "Battering Ram",
  8: "Catapult",
  9: "Mortar",
  10: "Gyrocopter",
  11: "Balloon-Bombardier",
  12: "Cook",
  13: "Doctor",
  14: "Barbarian-Axe Swinger",
  15: "Ram Ship",
  16: "Fire Ship",
  17: "Paddle Speedboat",
  18: "Ballista Ship",
  19: "Catapult Ship",
  20: "Mortar Ship",
  21: "Diving Boat",
  22: "Steam Ram",
  23: "Rocket Ship",
  24: "Balloon Carrier",
  25: "Tender",
  26: "Wall",
};

const BACKGROUNDS = {
  0: "battlefield_land_A_D",
  1: "battlefield_sea_A_D",
  2: "battlefield_city_A_D",
  3: "battlefield_barb_A_D",
  4: "battlefield_city_city",
}
