const UNITS = {
  1: "Hoplite",
  2: "Steam Giant",
  3: "Spearmen",
  4: "Swordsman",
  5: "Slinger",
  6: "Archer",
  7: "Sulfur Carabineers",
  8: "Battering Ram",
  9: "Catapult",
  10: "Mortar",
  11: "Gyrocopter",
  12: "Balloon-Bombardier",
  13: "Cook",
  14: "Doctor",
  15: "Barbarian-Axe Swinger",
  16: "Ram Ship",
  17: "Fire Ship",
  18: "Paddle Speedboat",
  19: "Ballista Ship",
  20: "Catapult Ship",
  21: "Mortar Ship",
  22: "Diving Boat",
  23: "Merchant Ship",
  24: "Steam Ram",
  25: "Rocket Ship",
  26: "Balloon Carrier",
  27: "Tender",
  28: "Wall",
};

const BACKGROUNDS = {
  0: "battlefield_land_A_D",
  1: "battlefield_sea_A_D",
  2: "battlefield_city_A_D",
  3: "battlefield_barb_A_D",
  4: "battlefield_city_city",
}